Fix line count for epochs
togethercomputer/OpenChatKit pull request #149
Opened 2023-06-27 21:36 UTC by orangetin

2023-06-27 21:37 UTC, justusc requested changes

2023-06-27 21:37 UTC, justusc commented on training/tasks/data_loaders/data_utils.py
> +                    token_count += len(encoded_input)
Can you reverse these lines?

2023-06-27 21:39 UTC, justusc approved these changes

2023-06-27 21:39 UTC, merged

2023-06-29 06:32 UTC, csris commented on training/tasks/data_loaders/data_utils.py
> +                    if line.replace(" ", "") != "\n":
@orangetin, is this trying to do

```python
if line.strip() != "":
```

or

```python
if len(line.strip() > 0):
```

2025-01-12 08:02 UTC, Scutua approved these changes